export class Candidate {
    public CandidateId: number;
    public DateResumeSent: Date;
    public Client: string;
    public JobNumber: boolean;
    public Name: number;
    public Experience: number;
    public CurrentSalary: number;
    public ExpectedSalary: number;
    public NoticePeriod: number;
    public ContactNumber: number;
    public Email: string;
    public SkypeId: string;
    public CurrentCompany: string;
    public VisaCompany: string;
    public CurrentCompanyVisaType: string;
    public CurrentLocation: string;
    public Nationality: string;
    public MaritalStatus: boolean;
    public DateOfBirth: Date;
    public PassportNumber: number;
    public RecruiterName: string;
    public ClosureType: string;
    public ResumeSource: string;
    public BackgroundCheckrequired: boolean;
    public Status: string;
    public ReasonForRejection: string;
    public Remark: string;
}
